_BASE_RUN: ../../pool/run/training/from_scratch_large.yaml
_BASE_MODEL: ../../pool/backbone/tadaformer_b16.yaml

PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: true
  DATASET: ssv2
  BATCH_SIZE: 256
  FINE_TUNE: true
  LR_REDUCE: true
  INIT: clip
  CHECKPOINT_FILE_PATH: ""
TEST:
  ENABLE: true
  DATASET: ssv2
  BATCH_SIZE: 256
DATA:
  DATA_ROOT_DIR: /mnt/ziyuan/ziyuan/ssv2/videos_mp4/
  ANNO_DIR: /mnt/ziyuan/ziyuan/ssv2/labels/
  SAMPLING_MODE: segment_based
  NUM_INPUT_FRAMES: 16
  TRAIN_JITTER_SCALES: [0.08, 1.0]
  TRAIN_CROP_SIZE: 224
  TEST_SCALE: 224
  TEST_CROP_SIZE: 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
VIDEO:
  BACKBONE:
    TEMP_ENHANCE: true
    DOUBLE_TADA: true
  HEAD:
    NUM_CLASSES: 174
    DROPOUT_RATE: 0.5

OUTPUT_DIR: output/tadaformer_b16_ssv2_16f

OPTIMIZER:
  BASE_LR: 5e-4
  ADJUST_LR: false
  LR_POLICY: cosine_v2
  COSINE_END_LR: 1e-6
  COSINE_AFTER_WARMUP: true
  MAX_EPOCH: 24
  MOMENTUM: 0.9 
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 4
  WARMUP_START_LR: 1e-8
  OPTIM_METHOD: adamw
  DAMPENING: 0.0
  NESTEROV: true
  HEAD_LRMULT: 10
  NEW_PARAMS: ["tada"]
  NEW_PARAMS_MULT: 10
  LAYER_WISE_LR_DECAY: 0.7
AUGMENTATION: 
  COLOR_AUG: true
  GRAYSCALE: 0.2
  COLOR_P: 0.0
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: false
  IS_SPLIT: false
  USE_GPU: false
  SSV2_FLIP: true
  RATIO: [0.75, 1.333]
  MIXUP: 
    ENABLE: false
  CUTMIX: 
    ENABLE: false
  RANDOM_ERASING:
    ENABLE: false
  LABEL_SMOOTHING: 0.1
  AUTOAUGMENT:
    ENABLE: true
    BEFORE_CROP: true
    TYPE: rand-m9-n4-mstd0.5-inc1
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 12
  PIN_MEMORY: true